name: Python package

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  create:
    branches: [main]
    tags: ['**']
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install stuff for PyQt
      run: |
        sudo -E apt-get install --no-install-recommends -y \
        openmpi-bin lsof \
        libfontconfig1 libxext6 libx11-xcb1 libxcb-glx0 \
        libxkbcommon-x11-0 	libgl1-mesa-glx \
        libncurses5 libreadline5 libdbus-1-3 libopenmpi-dev \
        libc6-dev libtinfo-dev libncurses5-dev \
        libx11-dev libreadline-dev \
        libxcb-icccm4 libxcb-util1 libxcb-image0 libxcb-keysyms1 \
        libxcb-render0 libxcb-shape0 libxcb-randr0 libxcb-render-util0 \
        libxcb-xinerama0 libxcb-xfixes0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-qt pytest-cov mne
        pip install hnn_core

    - name: Install HNN
      run: |
        python setup.py install

    - name: Lint with flake8
      run: |
        flake8 --count hnn
    - name: Test with pytest
      run: |
        python -m py.test .  --cov=hnn hnn/tests/ --cov-report=xml
